name: Test workflow

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Test app
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Echo the name
        run: |
          export NAME=Michael
          echo $NAME

      - name: Release app
        run: npm run release

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'joke-app-m' #Must be unique in Heroku
          heroku_email: 'michaeldemadet@gmail.com'
